name: CI
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
#      - name: Checkout repo
#        run: |
#          rm -rf ${{github.event.repository.name}}
#          git clone https://${{github.repository_owner}}:${{github.token}}@github.com/${{github.repository}}
#          git -C "${{github.workspace}}/${{github.event.repository.name}}" checkout ${{github.ref}}
      - name: java unit test
        run: | 
          mvn test --file pom.xml